name: Run nbmake for the main Branch

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:

    - name: Checkout files in repo
      uses: actions/checkout@v3

    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: cfr-env
        environment-file: environment.yml
        python-version: "3.10"
        auto-activate-base: false

    - name: Conda list
      run: |
        conda activate cfr-env
        pip install pytest pytest-xdist nbmake
        conda list

    - name: Test with pytest
      run: |
        conda activate cfr-env
        pytest --nbmake -k 'proxy and not psm and not test' -n=auto --nbmake-timeout=3000 --overwrite ./docsrc/notebooks/*.ipynb